version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ressearch
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - postgres
    entrypoint: ["java", "-jar", "/app.jar"]

  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ressearch
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
