package ru.xorochki.resSearch.model;

public enum CuisineType {
    RUSSIAN, ITALIAN, CHINESE, JAPANESE, MEXICAN, INDIAN, THAI, FRENCH, GREEK, SPANISH, CAMBODIAN,
    LEBANESE, AFRICAN, AMERICAN, ASIAN, AUSTRALIAN, BRAZILIAN, GERMAN, INDONESIAN

}
